### ISSUE TITLE
0.107.b0+

### ISSUE THREAD

**Issue by roblandry** [dmulcahey/zha-network-card#12]
```
Uncaught ReferenceError: transpose is not defined
    at zha-network-card.js:3
```

**Comment by ALERTua** [comment]
same here
`2020-03-15 12:32:32 ERROR (MainThread) [frontend.js.latest.202003130] http://hassio.local:8123/hacsfiles/zha-network-card/zha-network-card.js:3:11 Uncaught ReferenceError: transpose is not defined`

**Comment by jeepotvin** [comment]
```
Logger: frontend.js.latest.202002205
First occured: 10:56:34 AM (1 occurences)
Last logged: 10:56:34 AM
```

`https://xxxxxxxx/community_plugin/zha-network-card/zha-network-card.js:3:11 Uncaught ReferenceError: transpose is not defined`

Same error here but running 0.106.6

**Comment by roblandry** [comment]
change it to this in the js file and delete the gz file. if you want the gz file, then you will have to create the zip again.  i am not sure listify needs the var in front of it, but it worked for transpose, so i added it to listify also. i dont know anything about js, just trial and error, lol.

```js
var transpose = m => m[0].map((x, i) => m.map(x => x[i]));

// single items -> Array with item with length == 1
var listify = obj => (obj instanceof Array ? obj : [obj]);
```

**Comment by JamesDenby** [comment]
I have the same problem on 108.3

**Comment by ryan8382** [comment]
Same issue in 109.1
