### ISSUE TITLE
transpose is not defined

### ISSUE THREAD

**Issue by Veldkornet** [dmulcahey/zha-network-card#15]
HomeAssistant: 0.109
Zha-network-card: 753d254
I seem to be getting the below recently every time I open up HomeAssistant (not even clicking on the panel)
`2020-04-30 19:07:45 ERROR (MainThread) [frontend.js.latest.202004271] http://hassio.local:8123/hacsfiles/zha-network-card/zha-network-card.js:3:11 Uncaught ReferenceError: transpose is not defined`

**Comment by cannfoddr** [comment]
#12 fixed this for me
