### ISSUE TITLE
Devices no longer clickable after HA .112 update

### ISSUE THREAD

**Issue by Kanishkaz** [dmulcahey/zha-network-card#17]
The device rows in the table are no longer clickable to get more information since updating HA to v 0.112.

Could this be related to the refactoring of the ZHA config panel to the Integrations section of HA?

**Comment by blair287** [comment]
Yes same issues info in the tables seems to be working though.

**Comment by dmulcahey** [comment]
The dialog was removed when the UI was merged into the core UI in HA.
