### ISSUE TITLE
[Feature Request] Show device type

### ISSUE THREAD

**Issue by DrCoolzic** [dmulcahey/zha-network-card#24]
Would be nice if you could display the type of node: coordinator / router / end-device

**Comment by Adminiuga** [comment]
The shape displays it. And if you zoom in you should see the device type afaik

**Comment by DrCoolzic** [comment]
I guess you are talking about the graphics generated by the zha-network-visualization-card?
This is a request for the table generated by the zha-network-card. I have not seen an attribute with the node type information.

**Comment by Adminiuga** [comment]
ah, yep, you are right.

**Comment by popsyann** [comment]
On my config, I can see the device type:

type: 'custom:zha-network-card'
clickable: true
columns:
  - name: Name
    prop: name
  - attr: ieee
    name: IEEE Address
  - name: NWK
    prop: nwk
  - name: Type
    attr: device_type
sort_by: available

**Comment by DrCoolzic** [comment]
Yes you are right it works. Did not see it  in documentation. Probably my mistake

Documentation should add
```
  - attr: device_type
    name: Type
```
